### ISSUE TITLE
Question : Restore Filter setting

### ISSUE THREAD

**Issue by ollih1980** [coderazzi/tablefilter-swing#50]
Hi,

is it possible to restore a filter after updating the the data of a JTable? 

Thx a lot!

**Comment by coderazzi** [comment]
Hi, what do you mean with "restoring" a filter?

**Comment by ollih1980** [comment]
Hi,

I tried to store the filter settings during JTable refresh. I just found a way to manage this via : filterHeader.getFilterEditor(x).getContent();

Thx a lot!
